version: '3.6'
services:
  web:
    container_name: ${DOCKER_CONTAINER_NAME}
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: '${HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
      - '${SSH_PORT}:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '${SHM_SIZE}'